openapi: 3.0.3
info:
  title: Better Auth Compatible API
  description: Authentication endpoints for Humanoid Robotics Book
  version: 1.0.0
  contact:
    name: Backend Team
    url: https://hackathon1-production-aaf0.up.railway.app

servers:
  - url: https://hackathon1-production-aaf0.up.railway.app
    description: Production backend (Railway)
  - url: http://localhost:8000
    description: Local development

paths:
  /api/auth/sign-up/email:
    post:
      summary: Email signup
      description: Create new user account with email and password
      operationId: signUpEmail
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 6
                  example: password123
                name:
                  type: string
                  example: John Doe
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '400':
          description: Email already registered or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/sign-in/email:
    post:
      summary: Email sign-in
      description: Authenticate user with email and password
      operationId: signInEmail
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/sign-out:
    post:
      summary: Sign out
      description: Terminate user session
      operationId: signOut
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Sign out successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/session:
    get:
      summary: Get current session
      description: Retrieve current user session information
      operationId: getSession
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Session retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    allOf:
                      - $ref: '#/components/schemas/User'
                      - nullable: true
                  session:
                    allOf:
                      - type: object
                        properties:
                          token:
                            type: string
                      - nullable: true
        '401':
          description: Unauthorized (invalid or expired session)
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    nullable: true
                  session:
                    nullable: true
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "abc123xyz"
        email:
          type: string
          format: email
          example: "user@example.com"
        name:
          type: string
          example: "John Doe"
        emailVerified:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: "2025-12-18T10:30:00Z"

    Session:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGc..."
        expiresAt:
          type: string
          format: date-time
          example: "2025-12-25T10:30:00Z"

    Error:
      type: object
      properties:
        detail:
          type: string
          example: "Email already registered"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token
      description: Session token obtained from sign-up or sign-in
