import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Part 1: Foundations of Physical AI & Humanoid Robotics',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'part1-foundations' },
      ],
    },
    {
      type: 'category',
      label: 'Part 2: Module-Based Learning',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'part2-modules' },
      ],
    },
    {
      type: 'category',
      label: 'Part 3: Capstone - Building the Autonomous Humanoid',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'part3-capstone' },
      ],
    },
    {
      type: 'category',
      label: 'Part 4: Future of Humanoid Robotics',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'part4-future' },
      ],
    },
  ],
};

export default sidebars;
